#pragma once

#include "cuda_common.h"
#include "cuda_math.cuh"
#include "user_conf.cuh"

#define R 0
#define G 1
#define B 2
#define A 3

#define Y 0
#define Cr 1
#define Cb 2

#define DIFF_THRESHOLD 32
#define SAME_VALUE_FLAG 0
#define COUNT 1

// BLOCK_HEDDER_SIZE
// BLOCK INDEX: 2BYTE
// PIXEL DATA SIZE PER BLOCK: 3BYTE
#define BLOCK_HEDDER_SIZE 5
#define BLOCK_INDEX_BE 0
#define BLOCK_INDEX_LE 1
#define BLOCK_BIT_SIZE_B 2
#define BLOCK_BIT_SIZE_G 3
#define BLOCK_BIT_SIZE_R 4

#define ORG_COLOR_SIZE 4
#define DST_COLOR_SIZE 3

#define BLOCK_AXIS_SIZE	8
#define BLOCK_AXIS_SIZE_LOG2 3	// LOG2(BLOCK_AXIS_SIZE)

#define BLOCK_SIZE 64	// BLOCK_AXIS_SIZE * BLOCK_AXIS_SIZE
#define BLOCK_SIZE_LOG2 6	// LOG2(BLOCK_SIZE)


// BLOCK_SIZE * ORG_COLOR_SIZE
#define BLOCK_SIZE_ORG_COLOR 256
// LOG2(BLOCK_SIZE_ORG_COLOR)
#define BLOCK_SIZE_ORG_COLOR_LOG2 8


// BLOCK_SIZE * ENDIAN_SIZE
#define ENC_BUFFER_BLOCK_SIZE 128
// LOG2(ENC_BUFFER_BLOCK_SIZE)
#define ENC_BUFFER_BLOCK_SIZE_LOG2 7

// RUN(6BIT) + LEVEL(10BIT) = 2BYTE
#define ENDIAN_SIZE 2
// LOG2(ENDIAN_SIZE)
#define ENDIAN_SIZE_LOG2 1
